In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

def crawl_jobkorea(search_keyword):
    base_url = "https://www.jobkorea.co.kr"
    search_url = f"{base_url}/Search/?stext={search_keyword}"
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    
    try:
        response = requests.get(search_url, headers=headers)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # 채용공고 리스트 추출
        recruit_list = soup.select('article.list-item')
        
        data = {
            'site': [],
            'Col_Company': [],
            'Col_Recruit': [],
            'Col_detail': [],
            'Col_url': []
        }
        
        for recruit in recruit_list:
            # 회사명
            company_elem = recruit.select_one('a.corp-name-link.dev-view')
            company = company_elem.get_text(strip=True) if company_elem else 'N/A'
            
            # 채용공고 제목
            title_elem = recruit.select_one('a.information-title-link.dev-view')
            title = title_elem.get_text(strip=True) if title_elem else 'N/A'
            
            # 상세 조건 (경력, 학력 등)
            detail_elem = recruit.select_one('ul.chip-information-group')
            detail = detail_elem.get_text(strip=True) if detail_elem else 'N/A'
            
            # 채용공고 URL
            relative_url = title_elem['href'] if title_elem and 'href' in title_elem.attrs else ''
            full_url = base_url + relative_url if relative_url.startswith('/') else relative_url
            
            # 데이터 저장
            data['site'].append('Job_Korea')
            data['Col_Company'].append(company)
            data['Col_Recruit'].append(title)
            data['Col_detail'].append(detail)
            data['Col_url'].append(full_url)
        
        # 데이터프레임 생성
        df = pd.DataFrame(data)
        df.to_csv('data_jobkorea.csv', index=False, encoding='utf-8-sig')
        return df
    
    except Exception as e:
        print(f"Error occurred: {e}")
        return pd.DataFrame()

# '데이터분석'으로 검색한 채용공고 크롤링
df = crawl_jobkorea('데이터분석')
# 결과 출력
display(df)

,site,Col_Company,Col_Recruit,Col_detail,Col_url
0,Job_Korea,넛지헬스케어㈜,[캐시워크-병역특례]데이터분석담당 산업기능요원,경력무관학력무관병역특례서울 강남구D-5,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
1,Job_Korea,더치트주식회사,데이터 애널리스트 /데이터분석전문가 / 통계 전문가 / Data Analyst (통,경력무관대졸↑정규직 외서울 구로구D-22,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
2,Job_Korea,넛지헬스케어㈜,[캐시워크]데이터분석담당 채용전환형 인턴,신입대졸↑인턴서울 강남구D-8,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
3,Job_Korea,한패스㈜,[한패스(주)/데이터분석팀] Google Analytics데이터분석가,경력학력무관정규직서울 성동구D-4,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
4,Job_Korea,㈜메디젠휴먼케어,메디젠휴먼케어데이터분석담당 경력직 채용,경력3년↑석사↑정규직서울 송파구D-39,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
5,Job_Korea,연이,데이터분석준전문가 자격증 온라인 강의 교사 채용,경력2년↑학력무관프리랜서서울 광진구D-28,https://www.jobkorea.co.kr/Recruit/GI_Read/467...
6,Job_Korea,휴먼교육센터,[국비무료/숙식무료]AI/빅데이터분석/풀스택/KDT심화(무료숙식제공),신입·경력학력무관연수생/교육생서울 영등포구 외D-3,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
7,Job_Korea,(주)상상에프앤비,배달전문 프랜차이즈 기업 상상에프앤비 배달앱데이터분석전문가 채용,경력학력무관정규직경기 남양주시D-12,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
8,Job_Korea,㈜케이씨지소프트,모빌리티 플랫폼을 혁신할 기술영업 전문가와데이터분석전문가,경력3년↑초대졸↑정규직서울 성동구상시채용,https://www.jobkorea.co.kr/Recruit/GI_Read/464...
9,Job_Korea,㈜메이크인,[자체직전환/신입가능/여의도]나이스평가정보데이터분석채용,경력무관초대졸↑계약직 외서울 영등포구 외D-3,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
10,Job_Korea,한국정보기술㈜,[한국정보기술(주)] 수도권본부-교통센터데이터분석인력 채용,경력무관학력무관계약직경기 성남시D-2,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
11,Job_Korea,㈜이젠아카데미,ADSP자격증 빅데이터분석주말(토요일) 강의 강사님 채용,신입·경력초대졸↑정규직 외서울 서초구 외D-6,https://www.jobkorea.co.kr/Recruit/GI_Read/463...
12,Job_Korea,부산대학교 지능물류빅데이터연구소,[부산대KDT]개발자과정교육생모집(AI데이터분석풀스택웹개발자양성과정),신입대졸↑정규직부산 금정구상시채용,https://www.jobkorea.co.kr/Recruit/GI_Read/464...
13,Job_Korea,㈜큐핏,보험 상품 업무 및데이터분석신입 및 경력사원 채용,신입·경력2년↑대졸↑정규직서울 종로구D-8,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
14,Job_Korea,㈜파오스파트너스,"(주)파오스파트너스 -DB관리, DB생성, DB분석 채용",경력무관초대졸↑정규직서울 용산구D-14,https://www.jobkorea.co.kr/Recruit/GI_Read/464...
15,Job_Korea,글로빛㈜,"[글로빛] 빅데이터분석,AI(머신러닝,딥러닝) 가능한 박사님 모십니다",경력무관박사↑프리랜서서울 서초구상시채용,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
16,Job_Korea,잡코리아(유),[잡코리아] 영업기획 담당 (3년 이상),경력3년↑학력무관정규직서울 서초구D-5,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
17,Job_Korea,㈜써치엠,[마케팅지원팀-신입/경력] 매체정산/영업지원/데이터분석/매체커뮤니케이션,신입·경력초대졸↑정규직서울 강남구D-2,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
18,Job_Korea,코웨이㈜,[코웨이]25년 3월 계약직 채용(데이터분석/업무지원/실험보조/품질관리),경력학력무관계약직서울 구로구상시채용,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
19,Job_Korea,㈜싸이트플래닝건축사사무소,"도시공학&데이터분석공고 모집 (정규직, 경력직) [부산]",경력3년↑대졸↑정규직부산 동구D-15,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
20,Job_Korea,N/A,N/A,신입·경력고졸↑정규직서울 외D-2,
21,Job_Korea,N/A,N/A,신입·경력학력무관정규직경기오늘마감,
22,Job_Korea,N/A,N/A,신입·경력고졸↑정규직경기 외D-15,
23,Job_Korea,N/A,N/A,경력무관학력무관정규직인천 외D-5,
24,Job_Korea,N/A,N/A,신입·경력학력무관정규직 외서울D-29,
25,Job_Korea,N/A,N/A,신입·경력학력무관정규직경기D-18,
26,Job_Korea,N/A,N/A,신입·경력고졸↑계약직서울D-2,
27,Job_Korea,N/A,N/A,신입·경력고졸↑정규직서울 외상시채용,
28,Job_Korea,N/A,N/A,신입·경력학력무관정규직 외서울D-29,
29,Job_Korea,N/A,N/A,신입학력무관정규직서울오늘마감,
30,Job_Korea,N/A,N/A,D-12,
31,Job_Korea,N/A,N/A,D-13,
32,Job_Korea,N/A,N/A,D-12,
33,Job_Korea,N/A,N/A,D-9,
34,Job_Korea,N/A,N/A,D-13,
35,Job_Korea,N/A,N/A,D-20,
36,Job_Korea,N/A,N/A,D-30,
37,Job_Korea,N/A,N/A,D-29,
38,Job_Korea,N/A,N/A,"연봉29,000,000원경기 오산시 오산동등록일 13시간전마감일 상시모집",
39,Job_Korea,N/A,N/A,충남 아산시 배방읍등록일 3/30D-3,
40,Job_Korea,N/A,N/A,경기 안산시 상록구 본오동등록일 3/30D-3,
41,Job_Korea,N/A,N/A,"월급2,096,270원서울 성동구 성수동2가등록일 7시간전D-4",
42,Job_Korea,N/A,N/A,"건별10,030원서울 강남구 삼성동등록일 3/27마감일 상시모집",
43,Job_Korea,N/A,N/A,"월급2,096,270원대전 유성구 구룡동등록일 3/31마감일 상시모집",
44,Job_Korea,N/A,N/A,"월급2,096,270원서울 강남구 삼성동등록일 3/29마감일 상시모집",
45,Job_Korea,N/A,N/A,"시급30,000원인천 계양구 박촌동등록일 3/24D-3",
46,Job_Korea,N/A,N/A,"연봉29,000,000원경기 오산시 오산동등록일 3/24마감일 상시모집",
47,Job_Korea,N/A,N/A,"연봉29,000,000원경기 평택시 진위면등록일 3/24마감일 상시모집",
48,Job_Korea,N/A,N/A,"월급2,400,000원서울 서초구 양재동등록일 3/22D-6",
49,Job_Korea,N/A,N/A,"연봉29,000,000원경기 평택시 진위면등록일 3/31마감일 상시모집",
50,Job_Korea,N/A,N/A,경기 수원시 영통구 이의동등록일 3/30D-3,

In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

def crawl_jobkorea(search_keyword):
    base_url = "https://www.jobkorea.co.kr"
    search_url = f"{base_url}/Search/?stext={search_keyword}"
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    
    try:
        response = requests.get(search_url, headers=headers)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # 채용공고 리스트 추출
        recruit_list = soup.select('article.list-item')
        
        data = {
            'site': [],
            'Col_Company': [],
            'Col_Recruit': [],
            'Col_detail': [],
            'Col_url': []
        }
        
        for recruit in recruit_list:
            # 회사명
            company_elem = recruit.select_one('div.list-section-corp a.corp-name-link')
            company = company_elem.get_text(strip=True) if company_elem else 'N/A'
            
            # 채용공고 제목
            title_elem = recruit.select_one('div.information-title a.information-title-link')
            title = title_elem.get_text(strip=True) if title_elem else 'N/A'
            
            # 상세 조건 (경력, 학력, 지역 등)
            detail_elems = recruit.select('ul.chip-information-group li.chip-information-item')
            details = [elem.get_text(strip=True) for elem in detail_elems] if detail_elems else []
            detail = ' | '.join(details) if details else 'N/A'
            
            # 채용공고 URL
            title_link = recruit.select_one('div.information-title a.information-title-link')
            relative_url = title_link['href'] if title_link and 'href' in title_link.attrs else ''
            full_url = base_url + relative_url if relative_url.startswith('/') else relative_url
            
            # 데이터 저장
            data['site'].append('Job_Korea')
            data['Col_Company'].append(company)
            data['Col_Recruit'].append(title)
            data['Col_detail'].append(detail)
            data['Col_url'].append(full_url)
        
        # 데이터프레임 생성
        df = pd.DataFrame(data)
        df.to_csv('data_jobkorea.csv', index=False, encoding='utf-8-sig')
        return df
    
    except Exception as e:
        print(f"Error occurred: {e}")
        return pd.DataFrame()

# '데이터분석'으로 검색한 채용공고 크롤링
df = crawl_jobkorea('데이터분석')
# 결과 출력
display(df)

,site,Col_Company,Col_Recruit,Col_detail,Col_url
0,Job_Korea,더치트주식회사,데이터 애널리스트 /데이터분석전문가 / 통계 전문가 / Data Analyst (통,경력무관 | 대졸↑ | 정규직 외 | 서울 구로구 | D-22,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
1,Job_Korea,넛지헬스케어㈜,[캐시워크-병역특례]데이터분석담당 산업기능요원,경력무관 | 학력무관 | 병역특례 | 서울 강남구 | D-5,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
2,Job_Korea,㈜메디젠휴먼케어,메디젠휴먼케어데이터분석담당 경력직 채용,경력3년↑ | 석사↑ | 정규직 | 서울 송파구 | D-39,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
3,Job_Korea,넛지헬스케어㈜,[캐시워크]데이터분석담당 채용전환형 인턴,신입 | 대졸↑ | 인턴 | 서울 강남구 | D-8,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
4,Job_Korea,연이,데이터분석준전문가 자격증 온라인 강의 교사 채용,경력2년↑ | 학력무관 | 프리랜서 | 서울 광진구 | D-28,https://www.jobkorea.co.kr/Recruit/GI_Read/467...
5,Job_Korea,한패스㈜,[한패스(주)/데이터분석팀] Google Analytics데이터분석가,경력 | 학력무관 | 정규직 | 서울 성동구 | D-4,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
6,Job_Korea,휴먼교육센터,[국비무료/숙식무료]AI/빅데이터분석/풀스택/KDT심화(무료숙식제공),신입·경력 | 학력무관 | 연수생/교육생 | 서울 영등포구 외 | D-3,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
7,Job_Korea,(주)상상에프앤비,배달전문 프랜차이즈 기업 상상에프앤비 배달앱데이터분석전문가 채용,경력 | 학력무관 | 정규직 | 경기 남양주시 | D-12,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
8,Job_Korea,㈜케이씨지소프트,모빌리티 플랫폼을 혁신할 기술영업 전문가와데이터분석전문가,경력3년↑ | 초대졸↑ | 정규직 | 서울 성동구 | 상시채용,https://www.jobkorea.co.kr/Recruit/GI_Read/464...
9,Job_Korea,㈜메이크인,[자체직전환/신입가능/여의도]나이스평가정보데이터분석채용,경력무관 | 초대졸↑ | 계약직 외 | 서울 영등포구 외 | D-3,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
10,Job_Korea,㈜이젠아카데미,ADSP자격증 빅데이터분석주말(토요일) 강의 강사님 채용,신입·경력 | 초대졸↑ | 정규직 외 | 서울 서초구 외 | D-6,https://www.jobkorea.co.kr/Recruit/GI_Read/463...
11,Job_Korea,한국정보기술㈜,[한국정보기술(주)] 수도권본부-교통센터데이터분석인력 채용,경력무관 | 학력무관 | 계약직 | 경기 성남시 | D-2,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
12,Job_Korea,부산대학교 지능물류빅데이터연구소,[부산대KDT]개발자과정교육생모집(AI데이터분석풀스택웹개발자양성과정),신입 | 대졸↑ | 정규직 | 부산 금정구 | 상시채용,https://www.jobkorea.co.kr/Recruit/GI_Read/464...
13,Job_Korea,㈜큐핏,보험 상품 업무 및데이터분석신입 및 경력사원 채용,신입·경력2년↑ | 대졸↑ | 정규직 | 서울 종로구 | D-8,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
14,Job_Korea,㈜파오스파트너스,"(주)파오스파트너스 -DB관리, DB생성, DB분석 채용",경력무관 | 초대졸↑ | 정규직 | 서울 용산구 | D-14,https://www.jobkorea.co.kr/Recruit/GI_Read/464...
15,Job_Korea,글로빛㈜,"[글로빛] 빅데이터분석,AI(머신러닝,딥러닝) 가능한 박사님 모십니다",경력무관 | 박사↑ | 프리랜서 | 서울 서초구 | 상시채용,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
16,Job_Korea,잡코리아(유),[잡코리아] 영업기획 담당 (3년 이상),경력3년↑ | 학력무관 | 정규직 | 서울 서초구 | D-5,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
17,Job_Korea,㈜써치엠,[마케팅지원팀-신입/경력] 매체정산/영업지원/데이터분석/매체커뮤니케이션,신입·경력 | 초대졸↑ | 정규직 | 서울 강남구 | D-2,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
18,Job_Korea,코웨이㈜,[코웨이]25년 3월 계약직 채용(데이터분석/업무지원/실험보조/품질관리),경력 | 학력무관 | 계약직 | 서울 구로구 | 상시채용,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
19,Job_Korea,㈜싸이트플래닝건축사사무소,"도시공학&데이터분석공고 모집 (정규직, 경력직) [부산]",경력3년↑ | 대졸↑ | 정규직 | 부산 동구 | D-15,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
20,Job_Korea,㈜비알팜,생산관리/생산부/제조생산/구매/QA/공무/웹 관리자 신입/경력 채용,신입·경력 | 학력무관 | 정규직 외 | 강원 | D-15,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
21,Job_Korea,CJ,2025년 CJ그룹 신입사원 모집,신입 | 대졸↑ | 정규직 | 서울 외 | D-2,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
22,Job_Korea,㈜에버라인,[에버라인] K-POP 음반사업부 운영/행사/이벤트,신입·경력 | 초대졸↑ | 정규직 | 서울 | D-11,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
23,Job_Korea,㈜트립닷컴코리아,[Trip.com] 트립닷컴 부문별 채용,경력무관 | 학력무관 | 계약직 | 서울 | D-5,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
24,Job_Korea,코웨이갤러리,[코웨이갤러리] 코웨이 직영 매장 매니저 채용,경력무관 | 학력무관 | 계약직 | 충북 외 | 오늘마감,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
25,Job_Korea,㈜에드케이,사무직 담당자 채용,신입·경력 | 학력무관 | 정규직 | 서울 외 | D-12,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
26,Job_Korea,AJ 네트웍스,AJ네트웍스 3월 수시채용,신입·경력 | 고졸↑ | 정규직 | 서울 외 | 상시채용,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
27,Job_Korea,㈜십사일동안,주식회사 십사일동안 각 부문별 채용,신입·경력 | 학력무관 | 정규직 외 | 서울 | D-29,https://www.jobkorea.co.kr/Recruit/GI_Read/460...
28,Job_Korea,㈜더에스엠씨그룹,[The SMC] AEㆍ퍼포먼스마케터ㆍ전략기획 신입/경력 채용,신입·경력 | 학력무관 | 정규직 | 서울 | D-33,https://www.jobkorea.co.kr/Recruit/GI_Read/465...
29,Job_Korea,대성산업㈜,[대성그룹] 각 부문별 신입/경력 채용,신입·경력 | 초대졸↑ | 정규직 외 | 경기 외 | 오늘마감,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
30,Job_Korea,N/A,2025년 상반기 라인그룹 경력/신입 공개채용,D-12,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
31,Job_Korea,N/A,2025년 신입/경력사원 채용,D-13,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
32,Job_Korea,N/A,2025년 각 부문 채용,D-12,https://www.jobkorea.co.kr/Recruit/GI_Read/466...
33,Job_Korea,N/A,2025년 상반기 신입/경력 공개채용,D-9,https://www.jobkorea.co.kr/Recruit/GI_Read/467...
34,Job_Korea,N/A,2025년 상반기 부문별 대졸 신입사원 채용,D-13,https://www.jobkorea.co.kr/Recruit/GI_Read/467...
35,Job_Korea,N/A,2025 신입 및 경력 채용,D-20,https://www.jobkorea.co.kr/Recruit/GI_Read/467...
36,Job_Korea,N/A,신입 및 경력 사원 채용,D-30,https://www.jobkorea.co.kr/Recruit/GI_Read/467...
37,Job_Korea,N/A,각 부문별 신입/경력 채용,D-29,https://www.jobkorea.co.kr/Recruit/GI_Read/467...
38,Job_Korea,"#연구보조 및 측정,증량작업#고졸및전문대졸까지#연구보조","광학필름 연구보조 분석,측정 및 배합액 레진 작업등, 초보가능 급급","연봉29,000,000원 | 경기 오산시 오산동 | 등록일 14시간전 | 마감일 상시모집",https://www.albamon.com/jobs/detail/108722008?...
39,Job_Korea,휴먼교육센터,[국비무료/기숙사무료] AI심화/데이터분석/인공지능/풀스택(무료숙식제공),| 충남 아산시 배방읍 | 등록일 3/30 | D-3,https://www.albamon.com/jobs/detail/108538182?...
40,Job_Korea,휴먼교육센터,[국비무료/기숙사무료] AI심화/데이터분석/인공지능/풀스택(무료숙식제공),| 경기 안산시 상록구 본오동 | 등록일 3/30 | D-3,https://www.albamon.com/jobs/detail/108538157?...
41,Job_Korea,인터프로셀㈜,[성수/외국계기업] 환경분석 시험보조 채용,"월급2,096,270원 | 서울 성동구 성수동2가 | 등록일 7시간전 | D-4",https://www.albamon.com/jobs/detail/108731639?...
42,Job_Korea,디오브이매니지먼트 코리아 유한책임회사,"시장분석부터 딜소싱까지, AI/기술 기반 비즈니스 컨설턴트 모집","건별10,030원 | 서울 강남구 삼성동 | 등록일 3/27 | 마감일 상시모집",https://www.albamon.com/jobs/detail/108644649?...
43,Job_Korea,뉴클리어엔지니어링,야외추적자실험 지원 및 GC분석,"월급2,096,270원 | 대전 유성구 구룡동 | 등록일 3/31 | 마감일 상시모집",https://www.albamon.com/jobs/detail/108697558?...
44,Job_Korea,데이터분석,[SK자회사/2개월 단기] 데이터 분석 및 수집 아르바이트 직원 채용,"월급2,096,270원 | 서울 강남구 삼성동 | 등록일 3/29 | 마감일 상시모집",https://www.albamon.com/jobs/detail/108667285?...
45,Job_Korea,비앤브이솔루션 주식회사,"인천지역 중, 고등학교 빅데이터 / 인공지능 강사 모집 +[강사풀 등록]","시급30,000원 | 인천 계양구 박촌동 | 등록일 3/24 | D-3",https://www.albamon.com/jobs/detail/108575251?...
46,Job_Korea,"#연구보조 및 측정,증량작업#고졸및전문대졸까지#경력쌓기",광학필름 연구보조 및 레진 실험 준비 및 측정등 보조업무 초보가능,"연봉29,000,000원 | 경기 오산시 오산동 | 등록일 3/24 | 마감일 상시모집",https://www.albamon.com/jobs/detail/108575875?...
47,Job_Korea,"#연구보조 및 측정,증량작업#고졸및전문대졸까지#경력쌓기",필름배합액 연구보조 및 레진 실험 준비 및 측정등 보조업무 초보가능,"연봉29,000,000원 | 경기 평택시 진위면 | 등록일 3/24 | 마감일 상시모집",https://www.albamon.com/jobs/detail/108575031?...
48,Job_Korea,㈜메트릭스,[주1회 재택지원/사무보조] 데이터 분석 및 온라인 모니터링 담당자 채용,"월급2,400,000원 | 서울 서초구 양재동 | 등록일 3/22 | D-6",https://www.albamon.com/jobs/detail/108513038?...
49,Job_Korea,"#연구보조 및 측정,증량작업#고졸및전문대졸까지#연구보조","광학필름 연구보조 분석,측정 및 배합액 레진 작업등, 초보가능 급급","연봉29,000,000원 | 경기 평택시 진위면 | 등록일 3/31 | 마감일 상시모집",https://www.albamon.com/jobs/detail/108709550?...
50,Job_Korea,휴먼교육센터,[국비무료/기숙사무료] AI심화/데이터분석/인공지능/풀스택(무료숙식제공),| 경기 수원시 영통구 이의동 | 등록일 3/30 | D-3,https://www.albamon.com/jobs/detail/108538145?...